### ISSUE TITLE
Not building with ghc 7.8

### ISSUE THREAD

**Issue by nrnrnr** [haskell/HTTP#90]
Trying to build using ghc 7.8 on debian linux results in errors:

````
: nr@yorkie 10181 ; cabal configure
Resolving dependencies...
Configuring HTTP-4000.2.19...
: nr@yorkie 10182 ; cabal build
Preprocessing library HTTP-4000.2.19...
Preprocessing test suites for HTTP-4000.2.19...
Building HTTP-4000.2.19...
[ 1 of 18] Compiling Network.HTTP.MD5Aux ( Network/HTTP/MD5Aux.hs, dist/build/Network/HTTP/MD5Aux.o )

Network/HTTP/MD5Aux.hs:91:10: Warning:
    No explicit implementation for
      either ‘negate’ or ‘-’
    In the instance declaration for ‘Num ABCD’
[ 2 of 18] Compiling Paths_HTTP       ( dist/build/autogen/Paths_HTTP.hs, dist/build/Paths_HTTP.o )

dist/build/autogen/Paths_HTTP.hs:21:13: Not in scope: ‘catch’

dist/build/autogen/Paths_HTTP.hs:22:13: Not in scope: ‘catch’

dist/build/autogen/Paths_HTTP.hs:23:14: Not in scope: ‘catch’

dist/build/autogen/Paths_HTTP.hs:24:17: Not in scope: ‘catch’
````

I also found it a little strange that the version number cloned from github is one less than pulled from hackage.  But the hackage version seems to have similar issues (not building).

Please let me know if I can provide other info.

**Comment by hvr** [comment]
what's the output of `cabal configure -v2`? (I'm especially interested in the build-dep selection)

**Comment by hsenag** [comment]
FYI HTTP does work for me in GHC 7.8, and I routinely test with all the released GHC versions that the "build-tools" lists as being supported.

Apologies for the github version falling behind, I forgot to push the most recent release. Now fixed.

**Comment by hsenag** [comment]
Assuming this is ok now - please reopen with repro steps if not.
